<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Pneumatic_2Coil_Management" Id="{76a52a57-4e51-47e6-b62e-be1156308e1b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Pneumatic_2Coil_Management //V1.0
// Function block untuk mengolah faceplate dan watchdog pneumatic valve 2 coil
//	UDT dependencies:
	(*  
	1. stPneumatic2 v1.0 	*)

//	Changelog:
	(* 
	
	v1.0 [27.12.2021] Start development function block - Fabrilian Asali	
	v1.1 [24.05.2023] Add Pneumatic Name - Arif W*)	
	

VAR_INPUT
	bEnable						: BOOL;		
	bTriggerPneumaticRetract	: BOOL;
	bTriggerPneumaticAdvanced	: BOOL;
	bTriggerBoth				: BOOL;
	bReleaseBoth				: BOOL;
	bTestMode					: BOOL;
	bResetError					: BOOL;
	bBypassSensorRetract		: BOOL;
	bBypassSensorAdvanced		: BOOL;
	bBypassPreCheckSensor		: BOOL;
	xIn_SensorRetract			: BOOL;
	xIn_SensorAdvanced			: BOOL;
	TimerWatchdogRetract		: TIME := T#5S;
	TimerWatchdogAdvanced		: TIME := T#5S;
	TimerWatchdogPreRetract		: TIME := T#5S;
	TimerWatchdogPreAdvanced	: TIME := T#5S;
	TimerValve					: TIME := T#25MS;
	Name						: STRING;
END_VAR

VAR_OUTPUT
	bError						: BOOL;
	ErrorID						: INT;
	ErrorMsg					: STRING;
END_VAR

VAR_IN_OUT
	Pneumatic					: stPneumatic2;
END_VAR

VAR
	SeqIndex					: INT;
	SeqIndexAdv					: INT;
	SeqIndexRtc					: INT;
	InitSeqIndex				: INT;
	WatchdogTimer				: TON;
	ValveTimer					: TON;
	ValveTimerInit				: TON;
	bInit						: BOOL;
	PneuAdv						: R_TRIG;
	PneuRtc						: R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Init"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">136L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">137L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">129L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.iTestRetract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">154L</v>
                          </o>
                          <o>
                            <v n="Operand">"Pneumatic.iTestAdvanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">40L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"bTestMode"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">1</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">39L</v>
                        </o>
                        <v n="Id">38L</v>
                      </o>
                      <v n="Id">41L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">37L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.TestModeActive"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">45L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"bTestMode"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">44L</v>
                        </o>
                        <v n="Id">43L</v>
                      </o>
                      <v n="Id">46L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">42L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.iSensorRetract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">50L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"xIn_SensorRetract"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">49L</v>
                        </o>
                        <v n="Id">48L</v>
                      </o>
                      <v n="Id">51L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">47L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.iSensorAdvanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">55L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"xIn_SensorAdvanced"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">54L</v>
                        </o>
                        <v n="Id">53L</v>
                      </o>
                      <v n="Id">56L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">52L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.Error_Retract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">64L</v>
                          </o>
                          <o>
                            <v n="Operand">"Pneumatic.Error_Advanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">65L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"bResetError"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">63L</v>
                        </o>
                        <v n="Id">62L</v>
                      </o>
                      <v n="Id">66L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">57L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.Trigger_Retract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">2</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">126L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AND"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">"AND"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">108L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" />
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"bInit"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">111L</v>
                            </o>
                            <v n="Id">110L</v>
                          </o>
                          <o t="BoxTreeBox">
                            <v n="BoxType">"OR"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">112L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" />
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeBox">
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">114L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeOperand">
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.TestModeActive"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">1</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">117L</v>
                                    </o>
                                    <v n="Id">116L</v>
                                  </o>
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"bTriggerPneumaticRetract"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">16</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">119L</v>
                                    </o>
                                    <v n="Id">118L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">115L</v>
                              </o>
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">120L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeOperand">
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.TestModeActive"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">123L</v>
                                    </o>
                                    <v n="Id">122L</v>
                                  </o>
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.iTestRetract"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">16</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">125L</v>
                                    </o>
                                    <v n="Id">124L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">121L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <v n="CallType" t="Operator">Or</v>
                            <n n="EN" />
                            <n n="ENO" />
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">113L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">And</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">109L</v>
                      </o>
                      <v n="Id">127L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">107L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.Trigger_Advanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">2</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">76L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"AND"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">"AND"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">70L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" />
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"bInit"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">75L</v>
                            </o>
                            <v n="Id">74L</v>
                          </o>
                          <o t="BoxTreeBox">
                            <v n="BoxType">"OR"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">78L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" />
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeBox">
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">82L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeOperand">
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.TestModeActive"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">1</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">85L</v>
                                    </o>
                                    <v n="Id">84L</v>
                                  </o>
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"bTriggerPneumaticAdvanced"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">16</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">69L</v>
                                    </o>
                                    <v n="Id">68L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">83L</v>
                              </o>
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">102L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeOperand">
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.TestModeActive"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">105L</v>
                                    </o>
                                    <v n="Id">104L</v>
                                  </o>
                                  <o>
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"Pneumatic.iTestAdvanced"</v>
                                      <v n="Type">"BOOL"</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">16</v>
                                        <v n="Fixed">true</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">true</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">81L</v>
                                    </o>
                                    <v n="Id">80L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">103L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <v n="CallType" t="Operator">Or</v>
                            <n n="EN" />
                            <n n="ENO" />
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">79L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">And</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">71L</v>
                      </o>
                      <v n="Id">77L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">9L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"ValveManagement"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">224L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">225L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">223L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"Cycle"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">226L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" />
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" />
                        <l2 n="Types" />
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">false</v>
                      <v n="ENO">false</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">227L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">138L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.oPneumaticRetract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">2</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">165L</v>
                          </o>
                          <o>
                            <v n="Operand">"Pneumatic.oPneumaticAdvanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">2</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">163L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"bTriggerBoth"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">162L</v>
                        </o>
                        <v n="Id">161L</v>
                      </o>
                      <v n="Id">164L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">160L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"Pneumatic.oPneumaticRetract"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">168L</v>
                          </o>
                          <o>
                            <v n="Operand">"Pneumatic.oPneumaticAdvanced"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">3</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">166L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"bReleaseBoth"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">159L</v>
                        </o>
                        <v n="Id">158L</v>
                      </o>
                      <v n="Id">167L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">157L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="Cycle" Id="{0ac73b5f-61d9-4637-b8e3-ecc3ec4493f1}">
      <Implementation>
        <ST><![CDATA[// Pneumatic Advanced Cycle Counter
PneuAdv(CLK := Pneumatic.oPneumaticAdvanced AND Pneumatic.iSensorAdvanced); // Pemicu untuk menghitung siklus pneumatik maju dengan menghubungkan sinyal pengontrol dan sensor maju
IF PneuAdv.Q THEN // Jika siklus pneumatik maju terdeteksi
	Pneumatic.CyclePneuAdv := Pneumatic.CyclePneuAdv + 1; // Tambahkan satu ke hitungan siklus pneumatik maju
END_IF

// Pneumatic Retract Cycle Counter
PneuRtc(CLK := Pneumatic.oPneumaticRetract AND Pneumatic.iSensorRetract); // Pemicu untuk menghitung siklus pneumatik mundur dengan menghubungkan sinyal pengontrol dan sensor mundur
IF PneuRtc.Q THEN // Jika siklus pneumatik mundur terdeteksi
	Pneumatic.CyclePneuRtc := Pneumatic.CyclePneuRtc + 1; // Tambahkan satu ke hitungan siklus pneumatik mundur
END_IF

(*PneuAdv(CLK := Pneumatic.Trigger_Advanced);
CASE SeqIndexAdv OF
	0:
		IF PneuAdv.Q THEN
			Pneumatic.CyclePneuAdv	:= Pneumatic.CyclePneuAdv + 1;
			SeqIndexAdv				:= 1;
		END_IF
		
	1:
		IF NOT PneuAdv.Q THEN
			SeqIndexAdv				:= 0;
		END_IF
END_CASE

PneuRtc(CLK := Pneumatic.Trigger_Retract);
CASE SeqIndexRtc OF
	0:
		IF PneuRtc.Q THEN
			Pneumatic.CyclePneuRtc	:= Pneumatic.CyclePneuRtc + 1;
			SeqIndexRtc				:= 1;
		END_IF
		
	1:
		IF NOT PneuRtc.Q THEN
			SeqIndexRtc				:= 0;
		END_IF
END_CASE*)]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init" Id="{8d03c11a-dad1-4883-8630-a4dad8d8fdce}">
      <Implementation>
        <ST><![CDATA[// Reset Error Handling
IF bResetError THEN // Jika reset kesalahan diaktifkan
	bError := FALSE; // Set variabel bError ke FALSE untuk menunjukkan tidak ada kesalahan
	InitSeqIndex := 0; // Set indeks urutan inisialisasi kembali ke 0
END_IF

// Inisialisasi Pneumatic
IF bEnable AND NOT bInit THEN // Jika sistem diaktifkan dan belum diinisialisasi
	CASE InitSeqIndex OF // Berdasarkan indeks urutan inisialisasi
		0:
			IF xIn_SensorRetract THEN // Jika sensor retract aktif
				InitSeqIndex := 100; // Pergi ke langkah 100
			ELSIF xin_SensorAdvanced THEN // Jika sensor advanced aktif
				InitSeqIndex := 200; // Pergi ke langkah 200
			ELSIF NOT xIn_SensorRetract AND NOT xIn_SensorAdvanced THEN // Jika kedua sensor tidak aktif
				InitSeqIndex := 300; // Pergi ke langkah 300
			ELSE // Jika kedua sensor aktif pada saat inisialisasi
				ErrorID := 1; // Set ID kesalahan ke 1
				ErrorMsg := 'Both Sensor on at Init'; // Pesan kesalahan
				InitSeqIndex := 999; // Pergi ke langkah 999
			END_IF
	
		100:
			Pneumatic.oPneumaticRetract := TRUE; // Aktifkan pneumatik retract
			InitSeqIndex := 1000; // Pergi ke langkah 1000
		
		200:
			Pneumatic.oPneumaticAdvanced := TRUE; // Aktifkan pneumatik advanced
			InitSeqIndex := 1000; // Pergi ke langkah 1000
		
		300:
			Pneumatic.oPneumaticRetract := TRUE; // Aktifkan pneumatik retract
			Pneumatic.oPneumaticAdvanced := TRUE; // Aktifkan pneumatik advanced
			ValveTimerInit(In := TRUE, PT := TimerValve); // Aktifkan timer untuk inisialisasi katup
			IF ValveTimerInit.Q THEN // Jika timer katup aktif
			    ValveTimerInit(In := FALSE); // Nonaktifkan timer katup
				Pneumatic.oPneumaticAdvanced := FALSE; // Nonaktifkan pneumatik advanced
				Pneumatic.oPneumaticRetract := FALSE; // Nonaktifkan pneumatik retract
				InitSeqIndex := 1000; // Pergi ke langkah 1000
			END_IF;
		
		999:
			bError := TRUE; // Set variabel bError ke TRUE untuk menunjukkan kesalahan
		
		1000:
			bInit := TRUE; // Set variabel bInit ke TRUE untuk menunjukkan inisialisasi selesai
	END_CASE
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="ValveManagement" Id="{4e1eb282-b367-4946-8fce-1656a6a057ae}">
      <Implementation>
        <ST><![CDATA[// Reset Error Handling
IF bResetError THEN // Jika reset kesalahan diaktifkan
	bError := FALSE; // Set variabel bError ke FALSE untuk menunjukkan tidak ada kesalahan
	ErrorID := 0; // Set ID kesalahan kembali ke 0
	ErrorMsg := ''; // Kosongkan pesan kesalahan
	SeqIndex := 0; // Set indeks urutan kembali ke 0
END_IF

// Kontrol Pneumatik
IF bEnable AND bInit AND NOT bError THEN // Jika sistem diaktifkan, sudah diinisialisasi, dan tidak ada kesalahan
	CASE SeqIndex OF // Berdasarkan indeks urutan
		0: // Langkah awal
			IF Pneumatic.Trigger_Retract THEN // Jika triger retract aktif
				SeqIndex := 100; // Pergi ke langkah 100
			ELSIF Pneumatic.Trigger_Advanced THEN // Jika triger advanced aktif
				SeqIndex := 200; // Pergi ke langkah 200
			END_IF
			
		100: // Langkah untuk retract
			Pneumatic.Trigger_Retract := FALSE; // Nonaktifkan triger retract
			IF NOT bBypassPreCheckSensor THEN // Jika tidak melewati pengecekan sensor pra-retract
				WatchdogTimer(In := TRUE, PT := TimerWatchdogPreRetract); // Aktifkan timer pengawas pra-retract
				IF Pneumatic.iSensorAdvanced THEN // Jika sensor advanced aktif
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					SeqIndex := 105; // Pergi ke langkah 105
				ELSIF WatchdogTimer.Q THEN // Jika timer habis
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					Pneumatic.Error_Retract := TRUE; // Set kesalahan retract
					ErrorID := 10; // Set ID kesalahan
					ErrorMsg := CONCAT(Name, 'Error PreCheck Retract'); // Set pesan kesalahan
					SeqIndex := 999; // Pergi ke langkah 999
				END_IF
			ELSE
				SeqIndex := 105; // Pergi ke langkah 105
			END_IF
	
		105: // Langkah setelah pra-retract
			Pneumatic.oPneumaticRetract := TRUE; // Aktifkan pneumatik retract
			Pneumatic.oPneumaticAdvanced := TRUE; // Aktifkan pneumatik advanced
			ValveTimer(In := TRUE, PT := TimerValve); // Aktifkan timer katup
			IF ValveTimer.Q THEN // Jika timer katup aktif
				ValveTimer(In := FALSE); // Nonaktifkan timer
				Pneumatic.oPneumaticAdvanced := FALSE; // Nonaktifkan pneumatik advanced
				SeqIndex := 110; // Pergi ke langkah 110
			END_IF
			
		110: // Langkah setelah retract
			IF NOT bBypassSensorRetract THEN // Jika tidak melewati sensor retract
				WatchdogTimer(In := TRUE, PT := TimerWatchdogRetract); // Aktifkan timer pengawas retract
				IF Pneumatic.iSensorRetract THEN // Jika sensor retract aktif
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					SeqIndex := 0; // Kembali ke langkah awal
				ELSIF WatchdogTimer.Q THEN // Jika timer habis
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					Pneumatic.Error_Retract := TRUE; // Set kesalahan retract
					ErrorID := 11; // Set ID kesalahan
					ErrorMsg := CONCAT(Name, 'Error Watchdog Retract'); // Set pesan kesalahan
				END_IF
			ELSE
				SeqIndex := 0; // Kembali ke langkah awal
			END_IF
		
		200: // Langkah untuk advanced
			Pneumatic.Trigger_Advanced := FALSE; // Nonaktifkan triger advanced
			IF NOT bBypassPreCheckSensor THEN // Jika tidak melewati pengecekan sensor pra-advanced
				WatchdogTimer(In := TRUE, PT := TimerWatchdogPreAdvanced); // Aktifkan timer pengawas pra-advanced
				IF Pneumatic.iSensorRetract THEN // Jika sensor retract aktif
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					SeqIndex := 210; // Pergi ke langkah 210
				ELSIF WatchdogTimer.Q THEN // Jika timer habis
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					Pneumatic.Error_Advanced := TRUE; // Set kesalahan advanced
					ErrorID := 20; // Set ID kesalahan
					ErrorMsg := CONCAT(Name, 'Error PreCheck Advanced'); // Set pesan kesalahan
					SeqIndex := 999; // Pergi ke langkah 999
				END_IF
			ELSE
				SeqIndex := 205; // Pergi ke langkah 205
			END_IF				
		
		205: // Langkah setelah pra-advanced
			Pneumatic.oPneumaticRetract := TRUE; // Aktifkan pneumatik retract
			Pneumatic.oPneumaticAdvanced := TRUE; // Aktifkan pneumatik advanced
			ValveTimer(In := TRUE, PT := TimerValve); // Aktifkan timer katup
			IF ValveTimer.Q THEN // Jika timer katup aktif
				Pneumatic.oPneumaticRetract := FALSE; // Nonaktifkan pneumatik retract
				SeqIndex := 210; // Pergi ke langkah 210
			END_IF	
			
		210: // Langkah setelah advanced
			IF NOT bBypassSensorAdvanced THEN // Jika tidak melewati sensor advanced
				WatchdogTimer(In := TRUE, PT := TimerWatchdogAdvanced); // Aktifkan timer pengawas advanced
				IF Pneumatic.iSensorAdvanced THEN // Jika sensor advanced aktif
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					SeqIndex := 0; // Kembali ke langkah awal
				ELSIF WatchdogTimer.Q THEN // Jika timer habis
					WatchdogTimer(In := FALSE); // Nonaktifkan timer
					Pneumatic.Error_Advanced := TRUE; // Set kesalahan advanced
					ErrorID := 21; // Set ID kesalahan
					ErrorMsg := CONCAT(Name, 'Error Watchdog Advanced'); // Set pesan kesalahan
				END_IF
				ELSE
				SeqIndex	:= 0; // Kembali ke langkah awal
			END_IF					
	
		999: // Langkah jika ada kesalahan
			bError := TRUE; // Set variabel bError ke TRUE untuk menunjukkan ada kesalahan	
	
	END_CASE
	
ELSE // Jika tidak ada aktivitas
	SeqIndex := 0; // Set indeks urutan kembali ke 0
	WatchdogTimer(IN := FALSE); // Nonaktifkan timer pengawas
END_IF
]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>